In [1]:
!nvidia-smi

Wed Feb 18 15:54:53 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.57                 Driver Version: 581.57         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8              1W /  140W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(f"{torch.__version__=}\n{torch.cuda.is_available()=}")

torch.__version__='2.5.0'
torch.cuda.is_available()=True


# Tensor

## Creating Tensors
Tensors are created using `torch.tensor()`

By convention `Scaler` & `Vector` are created with lower-case variable names e.g. `x, y, scl, vct`

`Matrix` & `Tensor` are created with upper-case variable names e.g. `X, Y, MTX, TNSR`

In [3]:
scaler = torch.tensor(7)

print(f"{scaler=}") # Tensor Rank-0
print(f"{scaler.ndim=}") # Rank/N-Dimension
print(f"{scaler.shape=}") # Tensor Shape [Rows * Columns]
print(f"{scaler.item()=}") # Tensor in Python int

scaler=tensor(7)
scaler.ndim=0
scaler.shape=torch.Size([])
scaler.item()=7


In [4]:
vector = torch.tensor([7, 7])

print(f"{vector=}") # Tensor Rank-1
print(f"{vector.ndim=}")
print(f"{vector.shape=}")

vector=tensor([7, 7])
vector.ndim=1
vector.shape=torch.Size([2])


In [5]:
MATRIX = torch.tensor([[7, 8, 9],
                       [9, 10, 11]])
print(f"{MATRIX=}")
print(f"{MATRIX[0]=}")
print(f"{MATRIX[1]=}")
print(f"{MATRIX[0][1]=}")
print(f"{MATRIX.ndim=}")
print(f"{MATRIX.shape=}")

MATRIX=tensor([[ 7,  8,  9],
        [ 9, 10, 11]])
MATRIX[0]=tensor([7, 8, 9])
MATRIX[1]=tensor([ 9, 10, 11])
MATRIX[0][1]=tensor(8)
MATRIX.ndim=2
MATRIX.shape=torch.Size([2, 3])


In [6]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]])
print(f"{TENSOR=}")
print(f"{TENSOR.ndim=}")
print(f"{TENSOR.shape=}")

print(f"\n\n{TENSOR[0]=}")
print(f"\n{TENSOR[0][0]=}")
print(f"\n{TENSOR[0][0][0]=}")

TENSOR=tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])
TENSOR.ndim=3
TENSOR.shape=torch.Size([1, 3, 3])


TENSOR[0]=tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

TENSOR[0][0]=tensor([1, 2, 3])

TENSOR[0][0][0]=tensor(1)


In [7]:
TENSOR = torch.tensor(
    [
        [
            [
                [
                    [
                        [
                            [1, 2, 3, 4],
                            [3, 4, 5, 6],
                            [5, 6, 7, 8],
                            [7, 8, 9, 10]
                        ]
                    ],
                    [
                        [
                            [1, 2, 3, 4],
                            [3, 4, 5, 6],
                            [5, 6, 7, 8],
                            [7, 8, 9, 10]
                        ]
                    ]
                ]
            ]
        ]
    ]
)
print(f"{TENSOR=}")
print(f"{TENSOR.ndim=}")
print(f"{TENSOR.shape=}")

TENSOR=tensor([[[[[[[ 1,  2,  3,  4],
             [ 3,  4,  5,  6],
             [ 5,  6,  7,  8],
             [ 7,  8,  9, 10]]],


           [[[ 1,  2,  3,  4],
             [ 3,  4,  5,  6],
             [ 5,  6,  7,  8],
             [ 7,  8,  9, 10]]]]]]])
TENSOR.ndim=7
TENSOR.shape=torch.Size([1, 1, 1, 2, 1, 4, 4])


## Random Tensors

Random Tensors are tensors of a particular shape filled with random values. 

**Need for a Random Tensor:**

Many NNs learn in a way that they start with tensors full of random numbers, and they adjust those tensors as the learning progresses.

`Repeat(Start with Random Tensor -> Look at Data -> Update Random Tensor)`

In [8]:
RND_T = torch.rand(size=(3, 4)) ## Size/Shape

print(f"{RND_T=}")
print(f"{RND_T.ndim=}")
print(f"{RND_T.shape=}")

RND_T=tensor([[0.5389, 0.4362, 0.2512, 0.4399],
        [0.9336, 0.6093, 0.8441, 0.0155],
        [0.4417, 0.0697, 0.2548, 0.9262]])
RND_T.ndim=2
RND_T.shape=torch.Size([3, 4])


In [9]:
# Create image tensor with similar shape to an image tensor
random_image_tensor = torch.rand(3, 224, 224) # colour channels (R, G, B), height, width

print(f"{random_image_tensor=}")
print(f"{random_image_tensor.ndim=}")
print(f"{random_image_tensor.shape=}")

random_image_tensor=tensor([[[3.7117e-01, 6.9208e-01, 3.3687e-01,  ..., 6.0152e-01,
          8.6546e-01, 5.6793e-01],
         [4.0240e-01, 1.5116e-01, 2.1896e-01,  ..., 2.8412e-01,
          6.3682e-01, 1.3639e-01],
         [2.4533e-01, 4.5186e-01, 6.3742e-01,  ..., 2.1473e-01,
          7.3046e-01, 9.8955e-01],
         ...,
         [5.4897e-01, 9.7833e-02, 9.8793e-01,  ..., 2.6575e-01,
          6.6905e-01, 2.2179e-01],
         [1.6641e-01, 4.8678e-01, 5.8612e-01,  ..., 9.1407e-01,
          2.5903e-01, 7.3748e-01],
         [7.9875e-01, 7.3012e-01, 5.5011e-01,  ..., 2.3536e-01,
          5.4972e-01, 1.0204e-01]],

        [[3.4018e-01, 1.8549e-01, 2.3178e-01,  ..., 4.5959e-01,
          1.5298e-02, 9.6694e-01],
         [6.7468e-01, 5.9368e-01, 2.6844e-01,  ..., 6.1569e-02,
          5.4258e-02, 1.9444e-01],
         [8.9306e-01, 7.3017e-01, 3.4686e-01,  ..., 1.6046e-01,
          1.0747e-01, 2.9551e-01],
         ...,
         [3.8382e-01, 3.7997e-01, 1.6155e-03,  ..., 9.3503e

In [10]:
# Tensor of all Zeros
Z = torch.zeros(3, 4)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
# Tensor of all Ones
O = torch.ones(3, 4)
O

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
Z.dtype, O.dtype

(torch.float32, torch.float32)

## Creating a range of tensors & tensors-like

In [13]:
# torch.range() Deprecated & will be removed use torch.arange()
torch.range(0, 10)

C:\Users\shiva\AppData\Local\Temp\ipykernel_24832\2144373627.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
one_to_ten = torch.arange(0, 10)
print(f"{one_to_ten=}")

one_to_ten=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
R = torch.arange(start=0, end=1000, step=78)
print(f"{R=}")

R=tensor([  0,  78, 156, 234, 312, 390, 468, 546, 624, 702, 780, 858, 936])


In [16]:
# Creating tesnors like
# Used for creating a tensor having the same shape as another tensor we have
ten_zeroes =  torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
ten_ones =  torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
ten_rand =  torch.rand_like(one_to_ten.float()) # Rand need float values
ten_rand

tensor([0.9543, 0.2644, 0.6883, 0.6493, 0.3227, 0.6033, 0.0609, 0.2066, 0.2231,
        0.7280])

In [19]:
ten_rand =  torch.randn_like(one_to_ten.float()) # Rand need float values
ten_rand

tensor([-0.2726,  0.2635, -0.3057,  0.5011, -0.6276,  0.3636,  0.5284, -2.3800,
        -1.7821,  0.8654])

In [20]:
ten_rand =  torch.randint_like(one_to_ten, 1, 10)
ten_rand

tensor([4, 6, 5, 7, 2, 8, 9, 5, 4, 2])

## Tensor Data Types

- float16
- float32 (default)
- float64
- uint8 & int8
- unit16 & int16
- unit32 & int32
- unit64 & int64
- bool


      Note: Tensor datatypes is one of the 3 big errors that we usually run into with PyTorch & DL.
      1. Tensors not right datatype
      2. Tensors not right shape
      3. Tensors not on right device
  

In [21]:
# float32 Tensor
f32 = torch.tensor([3.0, 6.0, 9.0], # Values of the Tensor
                   dtype=None, # Data types of the tnsor
                   device=None, # What device is your tensor on
                   requires_grad=False # whether or not to track gradients with this tensors operations
                  )
print(f"{f32=}")
print(f"{f32.dtype=}")

f32=tensor([3., 6., 9.])
f32.dtype=torch.float32


In [22]:
# float16 Tensor (torch.float16 or torch.half)
f16 = torch.tensor([3.0, 6.0, 9.0], dtype=torch.half)
print(f"{f16=}")
print(f"{f16.dtype=}")

f16=tensor([3., 6., 9.], dtype=torch.float16)
f16.dtype=torch.float16


In [23]:
f32_to_16 = f32.type(torch.float16)
print(f"{f32_to_16=}")
print(f"{f32_to_16.dtype=}")

f32_to_16=tensor([3., 6., 9.], dtype=torch.float16)
f32_to_16.dtype=torch.float16


In [24]:
f32 * f16

tensor([ 9., 36., 81.])

In [25]:
(f16 * f32).dtype

torch.float32

In [26]:
x = torch.tensor([[1, -1], [1, 1]], dtype=torch.float32, requires_grad=True)
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [27]:
out = x.pow(2)
out

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)

In [28]:
out = out.sum()
out

tensor(4., grad_fn=<SumBackward0>)

In [29]:
out.backward()
out

tensor(4., grad_fn=<SumBackward0>)

In [30]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [31]:
x

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)

In [32]:
x.storage()

C:\Users\shiva\AppData\Local\Temp\ipykernel_24832\2674773268.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage()


 1.0
 -1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 4]

In [33]:
x.untyped_storage()

 0
 0
 128
 63
 0
 0
 128
 191
 0
 0
 128
 63
 0
 0
 128
 63
[torch.storage.UntypedStorage(device=cpu) of size 16]

### Getting information from Tensors (attributes)

1. Tensors datatype - `tensor.dtype`
2. Tensors shape - `tensor.shape` or `tensor.size()`
3. Tensors device - `tensor.device`

In [34]:
tsr = torch.rand(3, 4)
tsr

tensor([[0.8778, 0.4496, 0.4440, 0.8783],
        [0.1279, 0.6638, 0.6657, 0.4874],
        [0.7807, 0.8964, 0.8091, 0.9332]])

In [35]:
# Tensor Attributes
print(f"{tsr.dtype=}")
print(f"{tsr.shape=}")
print(f"{tsr.size()=}")
print(f"{tsr.ndim=}")
print(f"{tsr.device=}")

tsr.dtype=torch.float32
tsr.shape=torch.Size([3, 4])
tsr.size()=torch.Size([3, 4])
tsr.ndim=2
tsr.device=device(type='cpu')


In [36]:
tsr = tsr.to(torch.float16)
tsr

tensor([[0.8779, 0.4497, 0.4441, 0.8784],
        [0.1279, 0.6636, 0.6655, 0.4873],
        [0.7808, 0.8965, 0.8091, 0.9331]], dtype=torch.float16)

In [37]:
tsr = tsr.to(device='cuda')
tsr

tensor([[0.8779, 0.4497, 0.4441, 0.8784],
        [0.1279, 0.6636, 0.6655, 0.4873],
        [0.7808, 0.8965, 0.8091, 0.9331]], device='cuda:0',
       dtype=torch.float16)

## Manipulating Tensors (Tensor Operations)

- Addition
- Subtraction
- Multiplication (Element-wise)
- Division
- Matrix Multiplication

In [38]:
tsr = torch.tensor([1, 2, 3])
tsr

tensor([1, 2, 3])

In [39]:
tsr + 10

tensor([11, 12, 13])

In [40]:
tsr - 10

tensor([-9, -8, -7])

In [41]:
tsr * 10

tensor([10, 20, 30])

In [42]:
torch.mul(tsr, 10) # tsr * 10

tensor([10, 20, 30])

In [43]:
torch.add(tsr, 10) # tsr + 10

tensor([11, 12, 13])

In [44]:
torch.sub(tsr, 10) # tsr - 10

tensor([-9, -8, -7])

### Multiplication

There are 2 ways to perform multiplication

1. Element-Wise
2. Matrix Multiplication (Dot Product)

There are two rules for matrix Multiplication:
1. The **inner dimensions** must match: number of columns of T1 should be equal to number of rows of T2
   - `(3, 2) @ (3, 2)` won't Work
   - `(3, 2) @ (2, 3)` will Work
   - `(2, 3) @ (3, 2)` will Work
2. The resulting matrix has the shape of the **outer dimensions**: Number of rows in T1 and number of Columns in T2
   - `(3, 2) @ (2, 3)` -> `(3, 3)`
   - `(2, 3) @ (3, 2)` -> `(2, 2)`

In [45]:
# Element Wise
print(f"{tsr=}")
print(f"{tsr} * {tsr}", end=" = ")
print(f"{tsr*tsr}")

tsr=tensor([1, 2, 3])
tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [46]:
tsr @ tsr

tensor(14)

In [47]:
tsr = torch.arange(10000000)
tsr

tensor([      0,       1,       2,  ..., 9999997, 9999998, 9999999])

In [48]:
%%time
value = 0
for i in range(len(tsr)):
    value += tsr[i] * tsr[i]
print(value)

tensor(1291890006563070912)
CPU times: total: 48.5 s
Wall time: 49.1 s


In [49]:
%%time
tsr @ tsr

CPU times: total: 0 ns
Wall time: 2.23 ms


tensor(1291890006563070912)

In [50]:
T1 = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
T1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [51]:
T2 = torch.tensor(
    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
)
T2

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [52]:
T1 @ T2

tensor([[ 58,  64],
        [139, 154]])

In [53]:
TA = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)
TA

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [54]:
TB = torch.tensor(
    [
        [7, 10],
        [8, 11],
        [9, 12]
    ]
)
TB

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [55]:
# TA @ TB
# Throws: RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the shape issue we can manipulate the shape of one of our Tensors using **Transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [56]:
TB, TB.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [57]:
TA @ TB.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [58]:
TA.T @ TB

tensor([[ 76, 103],
        [100, 136]])

## Tensor Aggregation

Finding the min, max, mean, sum, etc.

In [59]:
X = torch.arange(0, 100, 10)
X

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
X.min()

tensor(0)

In [61]:
X.max()

tensor(90)

In [62]:
X.sum()

tensor(450)

In [63]:
X.mean(dtype=torch.float32)

tensor(45.)

In [64]:
X.median()

tensor(40)

In [65]:
X.mode()

torch.return_types.mode(
values=tensor(0),
indices=tensor(0))

In [66]:
X.argmin()

tensor(0)

In [67]:
X.argmax()

tensor(9)

In [68]:
X[9]

tensor(90)

## Reshaping, Stacking, Squeezing and Unsqueezing Tensors

- Reshaping: Reshape an input tensor to a defined/required shape
- View: Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking: combine multiple tensors on top of each other (V-Stack) or side-by-side (H-Stack)
- Squeeze: Removes all `1` dimensions from a tensor
- Unsqueeze: add a `1` dimensions to a tensor
- Permute: Return a view of the input width dimensions permuted (swapped) in a certain way

In [69]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
, # Reshape: Add an extra dimension
# The new shape needs to be compatible with the existing shape.
# Basically the nyumber of tensors in the source tensors should fit exactly in the new shape
# the New shapes multiplication should be equal to original shape
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
x[5] = 100
x, x_reshaped, z

(tensor([  1.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]),
 tensor([[  1.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]]),
 tensor([[  1.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]]))

In [73]:
z[:, 0] = 20
x, x_reshaped, z

(tensor([ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]),
 tensor([[ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]]),
 tensor([[ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]]))

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 20.,  20.,  20.,  20.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.],
        [100., 100., 100., 100.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.]])

In [75]:
# Stack tensors side-by-side of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]])

In [76]:
torch.vstack([x, x, x, x])

tensor([[ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.],
        [ 20.,   2.,   3.,   4.,   5., 100.,   7.,   8.,   9.]])

In [77]:
torch.hstack([x.view(9, 1), x.view(9, 1), x.view(9, 1), x.view(9, 1)])

tensor([[ 20.,  20.,  20.,  20.],
        [  2.,   2.,   2.,   2.],
        [  3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.],
        [100., 100., 100., 100.],
        [  7.,   7.,   7.,   7.],
        [  8.,   8.,   8.,   8.],
        [  9.,   9.,   9.,   9.]])

In [78]:
# Suezze removes all single dimesnisons from the tensor
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [79]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [80]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [81]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [82]:
y = torch.squeeze(x, 2)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [83]:
y = torch.squeeze(x, 3)
y, y.size()

(tensor([[[[0., 0.],
           [0., 0.]]],
 
 
         [[[0., 0.],
           [0., 0.]]]]),
 torch.Size([2, 1, 2, 2]))

In [84]:
y = torch.squeeze(x, (1, 3))
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [85]:
x = torch.tensor([1, 2, 3, 4])
x

tensor([1, 2, 3, 4])

In [86]:
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [87]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [88]:
torch.tensor(1).ndim

0

In [89]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [90]:
x = torch.reshape(x, [1, 9])
x, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
x_squeezed = torch.squeeze(x)

print(f"{x=}")
print(f"{x.shape=}")

print(f"\n{x_squeezed=}")
print(f"{x_squeezed.shape=}")

x=tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
x.shape=torch.Size([1, 9])

x_squeezed=tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
x_squeezed.shape=torch.Size([9])


In [92]:
x_unsqueezed = torch.unsqueeze(x_squeezed, 0)

print(f"{x_squeezed=}")
print(f"{x_squeezed.shape=}")

print(f"\n{x_unsqueezed=}")
print(f"{x_unsqueezed.shape=}")

x_squeezed=tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
x_squeezed.shape=torch.Size([9])

x_unsqueezed=tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
x_unsqueezed.shape=torch.Size([1, 9])


In [93]:
x_unsqueezed = torch.unsqueeze(x_squeezed, 1)

print(f"{x_squeezed=}")
print(f"{x_squeezed.shape=}")

print(f"\n{x_unsqueezed=}")
print(f"{x_unsqueezed.shape=}")

x_squeezed=tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
x_squeezed.shape=torch.Size([9])

x_unsqueezed=tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
x_unsqueezed.shape=torch.Size([9, 1])


In [94]:
# Permute
x = torch.randn(2, 3, 5)
x, x.shape

(tensor([[[-0.6780, -0.7304, -1.0064, -0.3291,  0.8365],
          [ 0.9857,  1.0701, -0.1077,  0.2761,  0.8346],
          [ 0.3395,  0.0344,  1.0247, -0.4818, -0.3041]],
 
         [[ 0.3412, -1.1009,  0.3947, -0.7393, -1.6428],
          [ 1.1190,  0.7898, -1.4694,  0.4987,  0.1521],
          [-1.1315,  1.4609, -0.6627, -0.2670,  1.6151]]]),
 torch.Size([2, 3, 5]))

In [95]:
y = torch.permute(x, (2, 0, 1))
y, y.shape

(tensor([[[-0.6780,  0.9857,  0.3395],
          [ 0.3412,  1.1190, -1.1315]],
 
         [[-0.7304,  1.0701,  0.0344],
          [-1.1009,  0.7898,  1.4609]],
 
         [[-1.0064, -0.1077,  1.0247],
          [ 0.3947, -1.4694, -0.6627]],
 
         [[-0.3291,  0.2761, -0.4818],
          [-0.7393,  0.4987, -0.2670]],
 
         [[ 0.8365,  0.8346, -0.3041],
          [-1.6428,  0.1521,  1.6151]]]),
 torch.Size([5, 2, 3]))

In [96]:
y = torch.permute(x, (2, 1, 0))
y, y.shape

(tensor([[[-0.6780,  0.3412],
          [ 0.9857,  1.1190],
          [ 0.3395, -1.1315]],
 
         [[-0.7304, -1.1009],
          [ 1.0701,  0.7898],
          [ 0.0344,  1.4609]],
 
         [[-1.0064,  0.3947],
          [-0.1077, -1.4694],
          [ 1.0247, -0.6627]],
 
         [[-0.3291, -0.7393],
          [ 0.2761,  0.4987],
          [-0.4818, -0.2670]],
 
         [[ 0.8365, -1.6428],
          [ 0.8346,  0.1521],
          [-0.3041,  1.6151]]]),
 torch.Size([5, 3, 2]))

In [97]:
y = torch.permute(x, (1, 2, 0))
y, y.shape

(tensor([[[-0.6780,  0.3412],
          [-0.7304, -1.1009],
          [-1.0064,  0.3947],
          [-0.3291, -0.7393],
          [ 0.8365, -1.6428]],
 
         [[ 0.9857,  1.1190],
          [ 1.0701,  0.7898],
          [-0.1077, -1.4694],
          [ 0.2761,  0.4987],
          [ 0.8346,  0.1521]],
 
         [[ 0.3395, -1.1315],
          [ 0.0344,  1.4609],
          [ 1.0247, -0.6627],
          [-0.4818, -0.2670],
          [-0.3041,  1.6151]]]),
 torch.Size([3, 5, 2]))

In [98]:
x = torch.rand(size=(224, 224, 3)) # height, width, color channel

# permute the original tensor to rearrange the axis/dim order
x_per = x.permute(2, 0, 1) # 3, 224, 224

print(f"{x=}")
print(f"{x.shape=}")
print(f"\n{x_per=}")
print(f"{x_per.shape=}")

x=tensor([[[2.4176e-01, 8.2324e-01, 9.4590e-01],
         [9.8353e-02, 2.4818e-01, 9.5458e-02],
         [8.7723e-02, 5.1068e-01, 5.1658e-01],
         ...,
         [4.6272e-01, 9.9273e-01, 8.1096e-01],
         [4.8365e-01, 1.5499e-01, 8.6150e-01],
         [1.8448e-01, 4.0723e-01, 9.6943e-01]],

        [[2.7731e-01, 3.2299e-01, 7.0894e-01],
         [1.2730e-01, 2.9242e-01, 3.1936e-01],
         [4.7034e-01, 9.6455e-01, 2.8302e-01],
         ...,
         [4.6873e-01, 7.1863e-02, 4.5493e-01],
         [2.3696e-01, 4.1405e-01, 1.2308e-01],
         [9.4068e-01, 3.2987e-01, 1.8161e-01]],

        [[4.8374e-01, 7.9259e-01, 1.2020e-01],
         [1.7687e-01, 7.2648e-01, 9.9804e-01],
         [7.8821e-01, 6.2013e-01, 4.1343e-02],
         ...,
         [5.3629e-02, 6.5942e-01, 6.8477e-01],
         [3.5646e-01, 5.8074e-02, 1.1133e-01],
         [2.4733e-01, 9.5708e-01, 3.7816e-01]],

        ...,

        [[9.1644e-01, 8.2040e-01, 9.5118e-01],
         [3.3520e-01, 3.8399e-01, 8.3320e-0

In [99]:
x[0, 0, 0] = 0 # since permute creates a view, changing the original memory chnages the views values as well

In [100]:
x_per

tensor([[[0.0000e+00, 9.8353e-02, 8.7723e-02,  ..., 4.6272e-01,
          4.8365e-01, 1.8448e-01],
         [2.7731e-01, 1.2730e-01, 4.7034e-01,  ..., 4.6873e-01,
          2.3696e-01, 9.4068e-01],
         [4.8374e-01, 1.7687e-01, 7.8821e-01,  ..., 5.3629e-02,
          3.5646e-01, 2.4733e-01],
         ...,
         [9.1644e-01, 3.3520e-01, 4.7003e-01,  ..., 4.8405e-01,
          1.8584e-01, 2.8666e-01],
         [1.8104e-01, 5.1828e-02, 3.4699e-01,  ..., 8.4136e-01,
          2.9363e-01, 9.6901e-01],
         [5.8408e-01, 9.6837e-01, 1.4274e-01,  ..., 1.9665e-01,
          9.4466e-01, 3.1344e-02]],

        [[8.2324e-01, 2.4818e-01, 5.1068e-01,  ..., 9.9273e-01,
          1.5499e-01, 4.0723e-01],
         [3.2299e-01, 2.9242e-01, 9.6455e-01,  ..., 7.1863e-02,
          4.1405e-01, 3.2987e-01],
         [7.9259e-01, 7.2648e-01, 6.2013e-01,  ..., 6.5942e-01,
          5.8074e-02, 9.5708e-01],
         ...,
         [8.2040e-01, 3.8399e-01, 5.3957e-02,  ..., 9.1791e-01,
          8.626

## Indexing (Selecting data from tensors)

Similar to Numpy

In [101]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [102]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [103]:
x[0][0] # x[0, 0] is same

tensor([1, 2, 3])

In [104]:
x[0, 0, 0]

tensor(1)

In [105]:
x[:, 0]

tensor([[1, 2, 3]])

In [106]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [107]:
x[:, 1, 1]

tensor([5])

In [108]:
x[0, 0, :]

tensor([1, 2, 3])

In [109]:
# Index to return 9
x[0, 2, 2]

tensor(9)

In [110]:
# Index to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch Tensors & NumPy

NumPy is popular scientific Python numerical computing library.

Pythorch has functionality to interact with it.

- Data in NumPy to PyTorch Tensor: `torch.from_numpy(ndarray)`
- Pytorch Tensor to NumPy: `torch.tensor.numpy()`

In [111]:
# NumPy to Tensor
arr = np.arange(1., 8.)
tsr = torch.from_numpy(arr) # Default dtype of numpy is float64 and tensor default dtype if float32. So tensor reflects that

arr, tsr

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [112]:
# Change value of array
arr = arr + 1
arr, tsr

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
# Tensor to NumPy
tsr = torch.ones(10)
arr = tsr.numpy()
tsr, arr

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [114]:
tsr += 1
tsr, arr

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [115]:
tsr[0] = 10
tsr, arr

(tensor([10.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.]),
 array([10.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.], dtype=float32))

In [116]:
tsr += 1
tsr, arr

(tensor([11.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.]),
 array([11.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.], dtype=float32))

In [117]:
tsr = tsr + 1
tsr, arr

(tensor([12.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.]),
 array([11.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.], dtype=float32))

## Reproducibility

For reproducibility, we need consistency across devices & different runs of the code. This can be done by turning off the randomness.

In [118]:
import torch

A = torch.rand(3, 4)
B = torch.rand(3, 4)

A, B, (A == B).all()

(tensor([[0.1088, 0.0329, 0.4306, 0.9552],
         [0.9925, 0.4110, 0.4915, 0.6457],
         [0.1222, 0.4887, 0.9070, 0.1045]]),
 tensor([[0.3100, 0.8284, 0.9369, 0.3028],
         [0.3050, 0.0271, 0.8121, 0.6460],
         [0.1291, 0.8641, 0.4860, 0.5550]]),
 tensor(False))

In [119]:
# Set random seed
torch.manual_seed(42)

In [120]:
torch.manual_seed(42)
C = torch.rand(3, 4)

torch.manual_seed(42)
D = torch.rand(3, 4)

C, D, (C == D).all()

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor(True))

## Running Tensors & Objects on GPUs

GPUs are capable of performing faster computations on numbers. 

In [121]:
!nvidia-smi

Wed Feb 18 15:55:46 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.57                 Driver Version: 581.57         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   39C    P8              1W /  140W |     147MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [122]:
import torch

torch.cuda.is_available()

True

In [123]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [124]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [125]:
# Create a tensor (defaults to CPU)
tensor1 = torch.tensor([1, 2, 3])
tensor1, tensor1.device

(tensor([1, 2, 3]), device(type='cpu'))

In [126]:
# Create a tensor (defaults to CPU)
tensor2 = torch.tensor([1, 2, 3], device=device)
tensor2, tensor2.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [127]:
# Move Tensor to a particular device. This creates a copy of the source tensor in the selected device.
tensor3 = tensor1.to(device)
tensor3, tensor3.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [128]:
tensor1[0] = 10
tensor1, tensor3

(tensor([10,  2,  3]), tensor([1, 2, 3], device='cuda:0'))

### Moving Tensors back to CPU

In [129]:
# If tensor is on GPU, it can't be converted to NumPy
t_cpu = tensor2.cpu()

In [130]:
t_cpu.numpy()

array([1, 2, 3])