# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tsr = torch.rand((7, 7))
tsr, tsr.shape

(tensor([[0.9716, 0.5208, 0.6716, 0.8175, 0.6211, 0.3477, 0.6292],
         [0.7307, 0.3787, 0.9905, 0.8715, 0.5032, 0.0632, 0.3619],
         [0.8115, 0.4062, 0.0882, 0.4521, 0.7762, 0.3082, 0.2529],
         [0.0778, 0.7239, 0.9435, 0.7748, 0.5645, 0.6739, 0.3747],
         [0.2136, 0.2951, 0.5009, 0.7437, 0.7190, 0.0306, 0.2733],
         [0.8295, 0.1608, 0.4946, 0.7568, 0.5404, 0.6018, 0.8478],
         [0.0440, 0.5468, 0.7851, 0.9392, 0.2602, 0.7084, 0.3278]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tsr2 = torch.rand((1,7))
print(tsr2, tsr2.shape)
tsr2_t = tsr2.T
print(tsr2_t, tsr2_t.shape)

# Perform matrix multiplication 
tsr @ tsr2_t

tensor([[0.9951, 0.8042, 0.3272, 0.0210, 0.8548, 0.2835, 0.5313]]) torch.Size([1, 7])
tensor([[0.9951],
        [0.8042],
        [0.3272],
        [0.0210],
        [0.8548],
        [0.2835],
        [0.5313]]) torch.Size([7, 1])


tensor([[2.5863],
        [2.0143],
        [2.0578],
        [1.8571],
        [1.3979],
        [2.2154],
        [1.3575]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
T1 = torch.rand((7, 7))
T2 = torch.rand((1, 7))

# Matrix multiply tensors
MM = T1 @ T2.T
MM, MM.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Create two random tensors on GPU
T1 = torch.rand((2, 3), device=device)
T2 = torch.rand((2, 3), device=device)

print(f"Device: {device}")
print((T1, T2))

Device: cuda
(tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0'), tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0'))



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
mm = T1 @ T2.T
mm, mm.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(f"{mm.max()=}")
# Find min
print(f"{mm.min()=}")

mm.max()=tensor(0.7668, device='cuda:0')
mm.min()=tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
# Find arg max
print(f"{mm.argmax()=}")

# Find arg min
print(f"{mm.argmin()=}")


mm.argmax()=tensor(1, device='cuda:0')
mm.argmin()=tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(0)

# Create random tensor
T = torch.rand((1, 1, 1, 10))
print(T, T.shape)

# Remove single dimensions
TS = T.squeeze()
print(TS, TS.shape)


# Print out tensors and their shapes


tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
           0.4556, 0.6323]]]]) torch.Size([1, 1, 1, 10])
tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
        0.6323]) torch.Size([10])
